trigger: none
pr: none
pool: "AWS-2XL"

parameters:
    - name: artifactName
      type: string
      default: "truera-trino-plugin"
    - name: trinoVersion
      type: string
      default: "406"


jobs:
  - job: build_truera_trino_plugin_and_publish
    pool:
        name: AWS-2XL
    steps:
        - bash: |
                set -e
                cd /tmp
                wget https://dlcdn.apache.org/maven/maven-3/3.9.3/binaries/apache-maven-3.9.3-bin.tar.gz
                tar xvf apache-maven-3.9.3-bin.tar.gz
                mkdir -p /tmp/maven_3_9_3
                cd /tmp/maven_3_9_3
                sudo cp -r /tmp/apache-maven-3.9.3/* .
          displayName: "Install mvn 3.9.3"
        - task: Maven@3
          inputs:
              mavenPomFile: "plugin/trino-truera/pom.xml"
              goals: clean install
              options: -DskipTests -Dair.check.skip-all=true -X
              publishJUnitResults: false
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.17"
              mavenVersionOption: 'Path'
              mavenDirectory: "/tmp/maven_3_9_3"
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              mavenOptions: "-Xmx4096m"
          displayName: "Maven build"
        - bash: |
                set -e
                cp "plugin/trino-truera/target/trino-truera-${TRUERA_TRINO_PLUGIN_VERSION}.zip" "${PUBLISH_DIRECTORY}"
                unzip -l "${PUBLISH_DIRECTORY"
          env:
                TRUERA_TRINO_PLUGIN_VERSION: ${{ parameters.trinoVersion }}
                PUBLISH_DIRECTORY: $(Build.ArtifactStagingDirectory)/truera
          displayName: "Copy zip file to separate folder"
        - task: UniversalPackages@0
          inputs:
            command: publish
            publishDirectory: '$(Build.ArtifactStagingDirectory)/truera'
            vstsFeedPublish: 'truera/truera-trino-plugin'
            vstsFeedPackagePublish: 'truera-trino-plugin'
            packagePublishDescription: 'Trino plugin description'
          displayName: "Publish universal package"
  - job: build_trino_querylog_plugin_and_publish
    pool:
        name: AWS-2XL
    steps:
        - bash: |
              set -e
              cd /tmp
              wget https://dlcdn.apache.org/maven/maven-3/3.9.3/binaries/apache-maven-3.9.3-bin.tar.gz
              tar xvf apache-maven-3.9.3-bin.tar.gz
              mkdir -p /tmp/maven_3_9_3
              cd /tmp/maven_3_9_3
              sudo cp -r /tmp/apache-maven-3.9.3/* .
          displayName: "Install mvn 3.9.3"
        - task: Maven@3
          inputs:
              mavenPomFile: "plugin/trino-querylog/pom.xml"
              goals: mvn clean package dependency:copy-dependencies
              options: -DincludeScope=runtime -DskipTests
              publishJUnitResults: false
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.17"
              mavenVersionOption: 'Path'
              mavenDirectory: "/tmp/maven_3_9_3"
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              mavenOptions: "-Xmx4096m"
          displayName: "Maven build"
        - bash: |
              set -e
              cp "plugin/trino-querylog/target/trino-querylog-${TRUERA_TRINO_PLUGIN_VERSION}-dist.zip" "${PUBLISH_DIRECTORY}"
              unzip -l "${PUBLISH_DIRECTORY}"
          env:
              TRUERA_TRINO_PLUGIN_VERSION: ${{ parameters.trinoVersion }}
              PUBLISH_DIRECTORY: $(Build.ArtifactStagingDirectory)/querylog
          displayName: "Copy jars to separate folder"
        - task: UniversalPackages@0
          inputs:
              command: publish
              publishDirectory: '$(Build.ArtifactStagingDirectory)/querylog'
              vstsFeedPublish: 'truera/trino-querylog-plugin'
              vstsFeedPackagePublish: 'trino-querylog-plugin'
              packagePublishDescription: 'Trino plugin description'
          displayName: "Publish universal package"
